# The URL the site will be built for
base_url = "https://aidengindin.com"

title = "Aiden Gindin"

theme = "terminimal"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feeds = true
minify_html = true

# Default language used in RSS and posts without a specific language
default_language = "en"

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

accent_color = "orange-auto"
background_color = "dark"

logo_text = "Aiden Gindin"

# Menu items
menu_items = [
    { name = "blog", url = "/blog", weight = 1 },
    { name = "portfolio", url = "/pages/portfolio", weight = 2 },
    { name = "github", url = "https://github.com/aidengindin", weight = 3 },
]

# Terminimal theme specific settings
# Show post word count and read time
show_word_count = true
show_reading_time = true

# Use full Hack font family
use_full_hack_font = true

# Optional: Set date format in blog post listings
date_format = "%B %e, %Y"
